enable_training: true
enable_live_ai_inference: true
enable_gpt_integration: true
trade_interval_seconds: 120
min_data_rows: 100

risk_controls:
  initial_spending_account: 50.0
  purchase_upper_limit_percent: 75.0
  minimum_buy_amount: 8.0
  max_position_value: 25.0

traded_pairs:
  - ETH/USD
  - XBT/USD
  - SOL/USD
  - ADA/USD
  - XRP/USD
  - LTC/USD
  - DOT/USD
  - MATIC/USD
  - LINK/USD
  - ATOM/USD
  - XMR/USD
  - TRX/USD
  - SHIB/USD
  - AVAX/USD
  - UNI/USD
  - APE/USD
  - FIL/USD
  - AAVE/USD
  - SAND/USD
  - CHZ/USD
  - GRT/USD
  - CRV/USD
  - COMP/USD
  - ALGO/USD
  - NEAR/USD
  - LDO/USD
  - XTZ/USD
  - EGLD/USD
  - KSM/USD
