enable_training: true
enable_live_ai_inference: true
enable_gpt_integration: true
trade_interval_seconds: 60

risk_controls:
  initial_spending_account: 10000.0   # total USD or fiat we have for all trades
  purchase_upper_limit_percent: 0.01  # means 1% of that total for a single trade => 100.0 max
  minimum_buy_amount: 20.0           # we refuse to buy under $20 worth
  max_position_value: 5000.0         # we won't hold more than $5k in any single sub-position
  # etc.

traded_pairs:
  - ETH/USD
  - XBT/USD
  - SOL/USD
  - ADA/USD
  - XRP/USD
  - LTC/USD
  - DOT/USD
  - MATIC/USD
  - LINK/USD
  - ATOM/USD
  - XMR/USD
  - TRX/USD
  - SHIB/USD
  - AVAX/USD
  - UNI/USD
  - APE/USD
  - FIL/USD
  - AAVE/USD
  - SAND/USD
  - CHZ/USD
  - GRT/USD
  - CRV/USD
  - COMP/USD
  - ALGO/USD
  - NEAR/USD
  - LDO/USD
  - XTZ/USD
  - EGLD/USD
  - KSM/USD
